### ISSUE TITLE
Replacer doesnt match underscore "_"

### ISSUE THREAD

**Issue by mrfr0g** [atecarlos/webpack-babel-jest#2]
We have SCSS files which include the underscore character like;

Feature_Component.scss

The current matcher doesn't capture the underscore character, for reference its;

```
.replace(/require\(\s*\'[a-zA-Z0-9\/\.\-\!]*\.(css|scss|less)\'\);/gm, '');
```

**Comment by atecarlos** [comment]
Merged pull request from @islautin. Let me know if that fixes the problem.

**Comment by mrfr0g** [comment]
@atecarlos it does, thanks
