### ISSUE TITLE
Missing dependency.

### ISSUE THREAD

**Issue by maxolasersquad** [atecarlos/webpack-babel-jest#5]
This project relies on babel-jest, but does not list it in the decencies. This is fixed in #4 , it just needs the PR.

I'm only putting this here because when I ran into this problem and didn't see anything in the issue tracker I began the process of creating my own PR. This is to help the next person to see the issue and the PR that fixes it.

**Comment by atecarlos** [comment]
@maxolasersquad thanks! This has been merged in.
